# Generated by Django 2.1.7 on 2019-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_user_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('final', models.DateField(blank=True, null=True, verbose_name='final')),
                ('resumo', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='experiencias',
            field=models.ManyToManyField(to='usuario.Experiencia'),
        ),
    ]
