# Generated by Django 2.1.7 on 2019-02-16 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20190216_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='experiencias',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
