# Generated by Django 2.1.7 on 2019-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20190216_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='resumo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
