# Generated by Django 2.1.7 on 2019-02-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20190216_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Candidato'),
        ),
    ]
