# Generated by Django 2.1.7 on 2019-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20190216_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
