# Generated by Django 2.1.7 on 2019-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('final', models.DateField(blank=True, null=True, verbose_name='final')),
                ('resumo', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('faixa_salarial', models.CharField(choices=[('Até 1.000', 'Até 1.000'), ('De 1.000 a 2.000', 'De 1.000 a 2.000'), ('De 2.000 a 3.000', 'De 2.000 a 3.000'), ('Acima de 3.000', 'Acima de 3.000')], default='Até 1.000', max_length=50)),
                ('escolaridade', models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Tecnólogo', 'Tecnólogo'), ('Ensino Superior', 'Ensino Superior'), ('Pós / MBA / Mestrado', 'Pós / MBA / Mestrado'), ('Doutorado', 'Doutorado')], default='Ensino Fundamental', max_length=50)),
                ('requisitos', models.TextField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
