# Generated by Django 2.1.7 on 2019-02-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Candidato', verbose_name='candidato'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Candidato', verbose_name='candidato'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='vaga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestao.Vaga', verbose_name='vaga'),
        ),
    ]
