# Generated by Django 2.1.7 on 2019-02-13 01:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20190212_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pretensao_salarial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('gestao.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('final', models.DateField(blank=True, null=True, verbose_name='final')),
                ('resumo', models.TextField(max_length=500)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Candidato', verbose_name='candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('final', models.DateField(blank=True, null=True, verbose_name='final')),
                ('resumo', models.TextField(max_length=500)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Candidato', verbose_name='candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
