# Generated by Django 2.1.7 on 2019-02-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_auto_20190214_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
