# Generated by Django 2.1.7 on 2019-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_auto_20190214_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='delete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
