# Generated by Django 2.1.7 on 2019-02-15 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0006_auto_20190215_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='candidato'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Vaga', verbose_name='vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacao',
            unique_together={('vaga', 'candidato')},
        ),
    ]
