# Generated by Django 2.1.7 on 2019-02-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_auto_20190215_0725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aplicacao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='vaga',
        ),
        migrations.DeleteModel(
            name='Aplicacao',
        ),
    ]
