# Generated by Django 2.1.7 on 2019-02-15 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0008_auto_20190215_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='candidato')),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='aplicacoes',
            field=models.ManyToManyField(editable=False, to='gestao.Aplicacao'),
        ),
    ]
