# Generated by Django 2.1.7 on 2019-02-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_auto_20190215_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='aplicacoes',
            field=models.ManyToManyField(blank=True, editable=False, null=True, to='gestao.Aplicacao'),
        ),
    ]
