# Generated by Django 2.1.7 on 2019-02-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_auto_20190215_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='candidato'),
        ),
    ]
