# Generated by Django 2.1.7 on 2019-02-16 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_auto_20190216_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='candidato'),
        ),
    ]
