# Generated by Django 2.1.7 on 2019-02-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_auto_20190216_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='candidato',
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
    ]
