# Generated by Django 2.1.7 on 2019-02-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_auto_20190216_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
