# Generated by Django 2.1.7 on 2019-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_vaga_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data',
            field=models.DateField(),
        ),
    ]
