# Generated by Django 2.1.7 on 2019-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_auto_20190216_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
